apiVersion: apps/v1
kind: Deployment
metadata:
  name: music
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
        - image: "yanivomc/spring-music:latest"
          name: music
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: music-service
spec:
  selector:
    app: music
  ports:
    - name: aport
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
